#############################################
# Stalwart Mail Server Configuration File   
#############################################

[server.listener."smtp"]
bind = ["[::]:25"]
protocol = "smtp"

[server.listener."submission"]
bind = ["[::]:587"]
protocol = "smtp"

[server.listener."submissions"]
bind = ["[::]:465"]
protocol = "smtp"
tls.implicit = true

[server.listener."imaptls"]
bind = ["[::]:993"]
protocol = "imap"
tls.implicit = true

[server.listener."sieve"]
bind = ["[::]:4190"]
protocol = "managesieve"

[server.listener."https"]
protocol = "http"
bind = ["[::]:443"]
tls.implicit = true

[server.listener."jmap"]
bind = ["[::]:8080"]
protocol = "http"
tls.implicit = true

[storage]
data = "rocksdb"
fts = "rocksdb"
blob = "rocksdb"
lookup = "rocksdb"
directory = "basemail"

[store."rocksdb"]
type = "rocksdb"
path = "%{env:STALWART_PATH}%/data"
compression = "lz4"

[directory."basemail"]
type = "basemail"
api_url = "%{env:AUTH_SERVER_URL}%"
chain_id = "%{env:CHAIN_ID}%"
rpc_url = "%{env:RPC_URL}%"
basemail_address = "%{env:BASEMAIL_ADDRESS}%"

store = "rocksdb"

[tracer."stdout"]
type = "stdout"
level = "info"
ansi = false
enable = true